apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: charts/authentik
      version: "2024.12.1"
      sourceRef:
        kind: GitRepository
        name: authentik
  interval: 50m
  values:
    authentik:
        secret_key: "PleaseGenerateASecureKey"
        error_reporting:
            enabled: true
        postgresql:
            password: "tHEj967RTzfMpcvfuMxvk4xClYh6TSng1Y9kFifSTUybYI5EvBtCTMotR0Y1c5Mhf9HSEg/r5/1zo2Zp"
    server:
        ingress:
            ingressClassName: traefik
            enabled: true
            hosts:
                - auth.evanhelbig.com
    postgresql:
        enabled: true
        auth:
            password: "tHEj967RTzfMpcvfuMxvk4xClYh6TSng1Y9kFifSTUybYI5EvBtCTMotR0Y1c5Mhf9HSEg/r5/1zo2Zp"
    redis:
        enabled: true