apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: https://auth.evanhelbig.com
    trustForwardHeader: true
    tls:
      insecureSkipVerify: true